services:
  db:
    image: postgres:17-bookworm
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?Configurar POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER:?Configurar POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Configurar POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
