worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream backend_pool {
        # Round Robin por defecto
        server app:3000 max_fails=2 fail_timeout=15s;
        server app2:3000 max_fails=2 fail_timeout=15s;
        server app3:3000 max_fails=2 fail_timeout=15s;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://backend_pool;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 2s;
            proxy_read_timeout 30s;
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_next_upstream_tries 3;
        }
    }
}
